# Site settings
title: Reno Blog
SEOTitle: Reno的博客 | Reno Blog
header-img: img/home-bg.jpg
email: lisikuanreno@gmail.com
description: "程序 生活 | 这里是 @Reno 的个人博客，与你一起发现更大的世界。"
keyword: "博客"
url: "lskreno.vip"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
weibo_username:     5092674629
zhihu_username:     sha-liao-ba-ta-40
github_username:    LSKReno
# twitter_username:   
#facebook_username:  Reno
#linkedin_username:  firstname-lastname-idxxxx



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN  



# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1



# Disqus settings
disqus_username: Reno

# Netease settings
netease_comment: false

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: cf0a5241582c0834dcc9                            #生成的clientID
  clientSecret: a3d38309fd2a8cacb333370b1510a389f3928b67    #生成的clientSecret
  repo: LSKReno.github.io    #仓库名称
  owner: LSKReno    #github用户名
  admin: LSKReno
  distractionFreeMode: true #是否启用类似FB的阴影遮罩



# Analytics settings
# Baidu Analytics 
# ba_track_id: [your track id]

# Google Analytics
# ga_track_id: 'your track id'            # Format: UA-xxxxxx-xx
# ga_domain: lskreno.vip



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "King and Begger, you and me <br>你我, 国王与乞丐"
sidebar-avatar: /img/avatar-hux-ny.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value

#search plugins
search: true                            # 是否使用搜索插件


# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false



# Friends
friends: [
    {
        title: "瞻彼淇奥",
        href: "https://colinzhang.cn/"
    },{
        title: "乱序",
        href: "http://mida.re/"
    },{
        title: "外刊评论",
        href: "http://qianduan.guru/"
    }
]
